#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff85295e228, pid=16548, tid=1000
#
# JRE version: Java(TM) SE Runtime Environment 18.9 (11.0.8+10) (build 11.0.8+10-LTS)
# Java VM: Java HotSpot(TM) 64-Bit Server VM 18.9 (11.0.8+10-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
# Problematic frame:
# C  0x00007ff85295e228  JPypeException::convertPythonToJava+0x158
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

---------------  S U M M A R Y ------------

Command Line: -Dfile.encoding=UTF8 -ea -Xmx1024m 

Host: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, 12 cores, 15G,  Windows 10 , 64 bit Build 17763 (10.0.17763.475)
Time: Thu Sep 24 17:06:08 2020 ¢¥eCN©öI¡¾©ö C¡ÍA¨ª¨öA elapsed time: 239 seconds (0d 0h 3m 59s)

---------------  T H R E A D  ---------------

Current thread (0x0000017117fa8800):  JavaThread "main" [_thread_in_native, id=1000, stack(0x0000002100800000,0x00000021009f0000)]

Stack: [0x0000002100800000,0x00000021009f0000],  sp=0x00000021009d6770,  free space=1881k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  0x00007ff85295e228  JPypeException::convertPythonToJava+0x158  (jp_exception.cpp:266)
C  0x00007ff85295d60a  JPypeException::toJava+0x1fa  (jp_exception.cpp:432)
C  0x00007ff85298faf9  `JPTypeFactory_rethrow'::`1'::catch$0+0x1d  (jp_typefactory.cpp:50)
C  [VCRUNTIME140.dll+0xc220]
C  [VCRUNTIME140.dll+0x29b2]
C  [ntdll.dll+0xa3ce6]
C  0x00007ff852972b4b  JPTypeFactory_rethrow+0x1b  (jp_typefactory.cpp:47)
C  0x00007ff85298facd  `JPTypeFactory_newWrapper'::`1'::catch$4+0x16  (jp_typefactory.cpp:97)
C  [VCRUNTIME140.dll+0xc220]
C  [VCRUNTIME140.dll+0x29b2]
C  [ntdll.dll+0xa3ce6]
C  0x00007ff852972ae2  JPTypeFactory_newWrapper+0x72  (jp_typefactory.cpp:97)
C  0x000001712fb1f037

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  org.jpype.manager.TypeFactoryNative.newWrapper(JJ)V+0
j  org.jpype.JPypeContext.newWrapper(J)V+16
v  ~StubRoutines::call_stub

siginfo: EXCEPTION_ACCESS_VIOLATION (0xc0000005), writing address 0x0000000000000000


Register to memory mapping:

RIP=0x00007ff85295e228 points into unknown readable memory: 48 ff 03 4c 8d 0d 9e dd
RAX=0x0 is NULL
RBX=0x0 is NULL
RCX=0x0000017125534940 points into unknown readable memory: 50 c6 c6 17 71 01 00 00
RDX=0x0000000000000006 is an unknown value
RSP=0x00000021009d6770 is pointing into the stack for thread: 0x0000017117fa8800
RBP=0x00000021009d8f30 is pointing into the stack for thread: 0x0000017117fa8800
RSI=0x0000017117c6c650 points into unknown readable memory: 60 4b 9a 52 f8 7f 00 00
RDI=0x0000000050810670 python36.dll